sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix -v

  # Check if Trait is synced with current PHPUnit version
  - php ./bin/compile.php
  - git diff --quiet

after_failure:
  - git diff
