name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
      - name: CodingStyle
        run: vendor/bin/php-cs-fixer fix -v
      - name: Check if Trait is synced with current PHPUnit version
        run: |
          bin/compile.php
          git diff --quiet
